// movie-vue/src/pages/Create.vue
<template>
  <div>
    <h1>영화 정보 추가</h1>
    <!-- v-model : React에서 value 지정 후 onChange -->
    <input type="text" v-model="movie.title" placeholder="영화 제목 입력" />
    <input type="text" v-model="movie.genre" placeholder="영화 장르 입력" />
    <input type="text" v-model="movie.actor" placeholder="영화 배우들 입력" />
    <button @click="sendMovie">영화 추가</button>
  </div>
</template>

<script>
import { addMovie } from "@/api/movie";

export default {
  name: "CreatePage",
  data() {
    return {
      movie: {
        // React에서 초기화 설정하던 역할
        title: "",
        genre: "",
        actor: "",
      },
    };
  },

  // 함수
  methods: {
    // 영화 추가 버튼 클릭 매서드
    async sendMovie() {
      await addMovie(this.movie);
      this.movie = { title: "", genre: "", actor: "" };
      this.$router.push("/"); // 홈 페이지로 이동
    },
  },
};
</script>

<style scoped lang="scss">
div {
  width: 900px;
  margin: auto;

  h1 {
    font-size: 2.5rem;
    font-weight: bold;
    margin-top: 30px;
    margin-bottom: 30px;
    text-align: center;
  }

  input {
    width: 100%;
    margin: 5px;
    padding: 5px;
    box-sizing: border-box;
  }
  button {
    margin: 5px;
    width: 100%;
    background: black;
    color: white;
    padding: 10px;
    cursor: pointer;
    font-weight: bold;
  }
}
</style>

// 5_React/7-router/src/pages/Create.js
import { addAnimal } from "../api/animal";
import { useState } from "react";
import styled from "styled-components";
import { useNavigate } from "react-router-dom"; // 추가 버튼 선택 시 홈으로 이동

const Div = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  height: calc(100vh - 70px);

  * {
    margin-right: 5px;
    padding: 5px;
  }

  button {
    background-color: black;
    color: white;
    border-radius: 5px;
    border: 1px solid black;
    cursor: pointer;
  }
`;

const Create = () => {
  const navigate = useNavigate();
  const [animal, setAnimal] = useState({}); // postman {}

  const add = async () => {
    await addAnimal(animal);
    navigate("/");
  };

  return (
    <Div>
      <input
        type="text"
        placeholder="동물 이름 입력"
        value={animal.name}
        onChange={
          (e) => setAnimal((prev) => ({ ...prev, name: e.target.value })) // ... : 기존 정보 포함 (age: prev.age 의 함축)
        }
      />
      <input
        type="text"
        placeholder="동물 나이 입력"
        value={animal.age}
        onChange={(e) =>
          setAnimal((prev) => ({ ...prev, age: e.target.value }))
        }
      />
      <button onClick={add}>동물 추가</button>
    </Div>
  );
};

export default Create;
